import simulation
# Test 1 for next function
ap = simulation.Airplane(2,2)
aisle = [(0,1), (1,0)]
bq = [(1,1), (0,0)]
ap.next(bq, aisle)
assert(ap.seating[1][0] == 1)
assert(ap.seating[0][1] == 1)
assert(ap.seating[0][0] == 0)
assert(ap.seating[1][1] == 0)
assert(aisle[0] == (1,1))
assert(aisle[1] == None)
print("Test1 next for simple example, case: People in their rows.")

# Test 2 for next function: passengars come in right order
ap = simulation.Airplane(2,2)
aisle = [None, None]
bq = [(1,0),(1,1), (0,1), (0,0)]
print("Test2 for a whole process:......")
ap.next(bq, aisle)
assert(ap.seating[1][0] == 0)
assert(ap.seating[0][1] == 0)
assert(ap.seating[0][0] == 0)
assert(ap.seating[1][1] == 0)
assert(aisle[0] == (1,0))
assert(aisle[1] == None)
assert(bq.size == 3)
print("First step passed...")
ap.next(bq, aisle)
assert(ap.seating[1][0] == 0)
assert(ap.seating[0][1] == 0)
assert(ap.seating[0][0] == 0)
assert(ap.seating[1][1] == 0)
assert(aisle[0] == (1,1))
assert(aisle[1] == (1,0))
assert(bq.size == 2)
print("Second step passed...")
ap.next(bq, aisle)
assert(ap.seating[1][0] == 1)
assert(ap.seating[0][1] == 0)
assert(ap.seating[0][0] == 0)
assert(ap.seating[1][1] == 0)
assert(aisle[0] == (0,1))
assert(aisle[1] == (1,1))
assert(bq.size == 1)
print("Third step passed...")
ap.next(bq, aisle)
assert(ap.seating[1][0] == 1)
assert(ap.seating[0][1] == 1)
assert(ap.seating[0][0] == 0)
assert(ap.seating[1][1] == 1)
assert(aisle[0] == (0,0))
assert(aisle[1] == None)
assert(bq.size == 0)
print("Forth step passed...")
ap.next(bq, aisle)
assert(ap.seating[1][0] == 1)
assert(ap.seating[0][1] == 1)
assert(ap.seating[0][0] == 1)
assert(ap.seating[1][1] == 1)
assert(aisle[0] == None)
assert(aisle[1] == None)
assert(bq.size == 0)
print("Test 2 passed")

# Test 3 for next function passengers come in reverse order
ap = simulation.Airplane(2,2)
aisle = [None, None]
bq = [(0,0),(1,1), (0,1), (1,0)]
print("Test2 for a whole process:......")
ap.next(bq, aisle)
assert(ap.seating[1][0] == 0)
assert(ap.seating[0][1] == 0)
assert(ap.seating[0][0] == 0)
assert(ap.seating[1][1] == 0)
assert(aisle[0] == (0,0))
assert(aisle[1] == None)
assert(bq.size == 3)
print("First step passed...")
ap.next(bq, aisle)
assert(ap.seating[1][0] == 0)
assert(ap.seating[0][1] == 0)
assert(ap.seating[0][0] == 1)
assert(ap.seating[1][1] == 0)
assert(aisle[0] == (1,1))
assert(aisle[1] == None)
assert(bq.size == 2)
print("Second step passed...")
ap.next(bq, aisle)
assert(ap.seating[1][0] == 1)
assert(ap.seating[0][1] == 0)
assert(ap.seating[0][0] == 0)
assert(ap.seating[1][1] == 0)
assert(aisle[0] == (0,1))
assert(aisle[1] == (1,1))
assert(bq.size == 1)
print("Third step passed...")
ap.next(bq, aisle)
assert(ap.seating[1][0] == 1)
assert(ap.seating[0][1] == 1)
assert(ap.seating[0][0] == 0)
assert(ap.seating[1][1] == 1)
assert(aisle[0] == (1,0))
assert(aisle[1] == None)
assert(bq.size == 0)
print("Forth step passed...")
ap.next(bq, aisle)
ap.next(bq, aisle)
assert(ap.seating[1][0] == 1)
assert(ap.seating[0][1] == 1)
assert(ap.seating[0][0] == 1)
assert(ap.seating[1][1] == 1)
assert(aisle[0] == None)
assert(aisle[1] == None)
assert(bq.size == 0)
print("Test 2 passed")